import { Link } from 'react-router-dom';
import './InfoDetailPage.css';

function RoadsPage() {
  return (
    <div className="info-detail-page">
      <header className="detail-header">
        <Link to="/gallery/0" className="back-button">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M19 12H5M12 19l-7-7 7-7"/>
          </svg>
          Back to Information
        </Link>
      </header>

      <div className="detail-content">
        <h1>Favorite Roads and Routes</h1>
        
        <div className="info-section">
          <p><em>By John R. Holt - Cofounder</em></p>
          
          <blockquote className="opening-quote">
            "In a car you're always in a compartment, and because you're used to it you don't realize that through that car window everything you see is just more TV. You're a passive observer and it is all moving by you boringly in a frame. On a cycle the frame is gone. You're completely in contact with it all. You're in the scene, not just watching it anymore, and the sense of presence is overwhelming. That concrete whizzing by 5 inches below your foot is the real thing, the same stuff you walk on, it's right there, so blurred you can't focus on it, yet you can put your foot down and touch it anytime, and the whole thing, the whole experience, is never removed from immediate consciousness." 
            <cite>Robert Persig, Zen and the Art of Motorcycle Maintenance.</cite>
          </blockquote>

          <p>
            I have visited a lot of places on my motorcycles, from the north rim of the Grand Canyon to the Cascade mountains to the Cabot Trail in northern Nova Scotia including a little side trip to "Meat Cove", where the road just ended at a cliff overlooking the St. Lawrence Bay. Since about 1970 or so, at least 95% of my riding, however, is within a long weekend of where I live. This is Chicken Run country. That area includes VA, WV, MD, Southwest PA, a little corner of southeast Ohio, the eastern third of TN and KY, and the western third of NC. This is Appalachia - great riding country! Motorcyclists from all over come here to ride. A great road can be any length. In my case it ranges from the 480-mile Blue Ridge Parkway to a short street near where I live. Other CR participants may have their favorites, but here in no particular order are my favorite roads in the Chicken Run riding area.
          </p>
          <p>
            <u>U.S. 219 from Huttonsville to Slaty Fork (Snowshoe), WV either direction</u>. This highway has a bit of everything - long see-through sweepers that can be taken at whatever speed your courage and skills allow, tight steep blind twisties that always get my full concentration and gentle straight-aways where you can relax and watch the scenery or pass the occasional 4-wheeler. This is my kind of road. The road is usually well maintained making it smooth and predictable. Traffic is usually light compared to other US highways in the area. I always seem to hit this stretch coming south late in the afternoon and north early in the morning. Either way is great. Five miles off this road is the Snowshoe ski resort. It's a great place to spend the night in the hot summer. This is where we stay on most CRs. There used to be a world class restaurant up there. The "Red Fox" was rated by “Fodars Travel Guide" as one of the 25 best restaurants in the country! But alas, the owners must have decided they could make more money running a place a little lower on the scale. Even so, there are still a few very good restaurants on top of the mountain. Route 219 from Slaty Fork to Marlinton, though very nice, didn't make my favorites list only because many of the tighter curves are often strewn with gravel - mostly due to guys in 4-wheel drive pickups with over-sized tires who can't seem to stay on the pavement. There is not so much on the northern section.
          </p>
          <p>
            <u>Highland Scenic Highway, route 150 between US 219 and 55/39 in WV either direction</u>. Even though the speed limit is 45, this is a good place to find out how well your bike is running if you dare. There are high-speed sweepers with plenty of visibility and very low traffic. There is certainly no reason to go less than 45. Be especially careful though in early morning and late evening. There is plenty of wildlife around. It's also a great place to stop at an overlook and enjoy the coolness and quiet of the high elevation. In fact, all of this part of WV is like a quick trip to Canada, and nobody lives up here. I have heard that this is the second largest wilderness area east of the Mississippi, the area in northern Maine being the only one larger.
          </p>
          <p>
            <u>Route 55/39 from WV 150 to Richwood, WV</u>. After being on the Highland Scenic Highway, riding down from the higher elevations on these gentle sweepers along the babbling brook gives the feeling of gliding in for a landing after a fast high flying airplane ride. This is probably my favorite stretch in the fall because the colors are so rich along here. I think the colors are so great because it rains a lot here. There's something about this micro-climate that if it is raining anywhere in the area, this stretch of road will get the most of it. Going the opposite direction (towards 150) doesn't seem as ethereal for some reason. 
          </p>
          <p>
            <u>Back Mountain Road between Edray (just north of Marlinton on 219) and Cass, WV either direction</u>. This tiny, single lane, narrow, slow-going but paved road is just simply a beautiful place to be, deep in the heart of the WV forest. My blood pressure seems to drop a few points every time I cruise through there - and it is definitely a cruising road. When you get to Cass, stop and get an ice cream cone at the country store. A ride on the scenic railroad is not out of the question either. If I retired there in my favorite little valley just east of Edray, I think I would live at least 10 years longer. Though I have never stayed there, part-way through the stretch in the little village of Stony Bottom, population probably about 12, is actually a 4-room motel. Talk about getting away from it all!
          </p>
          <p>
            <u>Highway 33 about 30 miles west of Harrisonburg, VA to the WV border on top of the mountain</u>. This is seven miles of steep up-hill elevation gain to get into WV. There are many tight well-banked twisters and even a few places you can blast around the creeping trucks and 4-wheelers. This was my buddy and CR cofounder John Lyons' best road. By that I mean that there are some roads that seem to fit different riders better than others. They seem to ride them better than other roads. I could never keep up with Lyons when he headed for the top of this mountain. The WV side of the mountain is only 3 miles and not near as interesting as the VA side. Keep going, however, toward Brandywine, WV. Brandywine is the site of the chicken in "Chicken Run". On the 3rd leg of the CR (the Fall Foliage Tour) when there is no chicken at the firehouse or when they sell out before we get there, we usually head on over to Franklin, a good bit larger town than Brandywine, where there are several restaurants. For the last few CRs we have stopped at Thompson’s restaurant where they have brought in a bar-b-que smoker where they make excellent North Carolina style Q.
          </p>
          <p>
            <u>Highway 28 from Judy Gap, WV (just west of Franklin) to Bartow, then Greenbank, WV</u>. This is one of those roads I just love, but I'm not quite sure why. There are few really challenging twisty curves to test ones skill, or spectacular vistas to photograph. It's just a ride through the woods. Maybe it's because, starting at Judy Gap, you start to slowly gain elevation ever so slightly without realizing it. Before you know it you are over 4,000 ft. (OK, for you people out west, this is pretty high for the East Coast.) Maybe its because I have ridden the stretch between 33 and 250 (25 miles or so) many times when the number of cars I met and passed totaled less than 5. Maybe its because you can often see herds of deer grazing in the fields. Maybe its because when its October in the late afternoon and the sun hits the trees just right, its like riding through a canyon of neon lights. At Bartow turn left and go to Greenbank. At Greenbank it's worthwhile to stop at the National Radio Observatory, run by the National Science Foundation and take a free tour. The last time I took the tour they had finished building a fully mobile new dish antenna that is 100 meters in diameter and is the largest movable dish antenna in the world! It is, of course, named after Sen. Robert Byrd, as is many other things in WV. It is one place where you can talk to people about SETI (Search for Extraterrestrial Intelligence) without getting laughed at.
          </p>
          <p>
            <u>Highway 28 from the Cass, WV turnoff to the intersection with Rt. 39 near Marlinton, WV</u>. This road goes through a scenic valley of small farms and woodlands. There are no steep mountains to go up or down. The road just follows the land, which is rolling hilly. The two words that come to mind are, "meandering" and "undulating". There are no really abrupt curves so one can take it pretty fast, (and I got a speeding ticket here once. I deserved it.), but the direction is constantly moving. Down left, up right, little dip, left, right, left, - there is a rhythm to this road. At high speed my adrenaline is flowing fast. It's more like making love to the road than riding it. YEEE-HAAAA!
          </p>
          <p>
            <u>Highway 20 from Buckhanon to Webster Springs, WV</u>. There is a bit of congestion around Buckhanon, but you get out of that after 5 miles or so. Then the fun begins. There are at least three mountain passes to go over before getting to Webster Springs, a distance of about 25 miles. The surface is usually in good condition and it is very challenging. This is the road for you if you like a lot of up and down curves. The only negative about this road is that often there is a good bit of traffic. Plan to hit this road in the morning to minimize traffic congestion. Traffic is so slow however one can often "dive-bomb" a pass because you can often see through the curve. A dive bomb is accomplished on a left hand curve when you can see through the curve. If no traffic is coming, you just dive the bike over to the left and cut the corner coming out fast just like a dive bomber. We often stop just west of Webster Springs for lunch at a hamburger joint that makes great burgers and milkshakes. Yum!
          </p>
          <br />
          <br />
          <p>
            All of the above roads can be ridden on a normal 3-day weekend Chicken Run. Sometimes, however, the CR is combined with other roads usually to the south for a longer ride, like maybe a week or more. On these occasions, the following are added to my favorites list. 
          </p>
          <p>
            <u>Blue Ridge Parkway from Cherokee, NC to Waynesboro, VA either direction</u>. This, of course, is probably on everybody's list that lives in the East. It seems inadequate that the BRP is mentioned only once. I could break it into 25-mile segments and they would all make my favorites list. There's something a little different every 25 miles or so, and it goes on for almost 500. In addition to great scenery, the road is always in good repair and there is rarely gravel on the road because they let the grass grow right up to the edge of the pavement. Like route 150 in WV, the only negative is the 45-MPH speed limit. My experience is that it is benignly enforced, not too stringently. Besides, this is the kind of road that invites one to take it easy and smell the roses. And, there are plenty of flowers, especially in the spring and late summer. For serious sport riding, an added bonus is the roads that run back and forth across the parkway, up and down the mountains, which are more technically challenging than the parkway itself. Equipped with the right kind of bike and a DeLorme contour map, one can even find some interesting dirt roads off the parkway to explore. One could easily spend a week along the parkway and side roads with very little backtracking. I highly recommend staying overnight at one of the motels on the parkway. At sundown, one can sit on the balcony or patio, which is attached to almost all rooms and watch the deer grazing in the meadow. No TV, telephone or highway noise, except the occasional Harley in the distance, interrupts one's reverie. I recall one clear spring night with Dave Sulser, at Otter's Peak sitting on the patio with a spectacular view of the Hale Bopp comet. We sat there and sipped Cognac while we watched the comet. Very peaceful. Incidentally, Skyline Drive, which continues from Wayneboro to Front Royal, VA does not make my favorites list because of the crowds, the Winnebagos, the toll and the more strictly enforced 35 MPH speed limit. 
          </p>
          <p>
            <u>The Cherahola Skyway near the NC/TN border</u>. This road was added to my favorites list in October 1999 when I rode the Cherahola for the first time. The Cherahola is sort of a cross between the route 150 Scenic Highway of WV and the Blueridge Parkway. Spectacular vistas high in the Smokies with paved fast sweepers one after another. My original plan in '99 was to make it part of a loop on a ride out of my motel in Townsend, TN. After riding it though, I turned right around and rode it in the opposite direction. After that ride, the Cherahola went from a road I had heard about, to a road near the top of my all time favorite motorcycle roads. What a ride!
          </p>
          <p>
            <u>Highway 129 for 11 miles west of Deals Gap, NC either direction</u>. Almost all of the road is in TN but it is known as "Deal's Gap" and many consider it motorcycle heaven. Anybody who lives east of the big river and considers him or herself a serious sport or sport-touring motorcyclist has probably been there. If you haven't, you really need to go there. It is nationally known with 318 curves in 11 miles. In fact, the only negative about this road is that it has become too popular. I wouldn't recommend going there on a weekend in good weather. I'm always too busy to count the curves, but I do know there are no straight stretches and according to my calculations, that's one curve every 183 feet, which sounds about right. Not only is it curvy, it is well-banked, clean surface, good visibility around most of the curves and serious fun in either direction. 4-wheel traffic is usually low, and the locals seem to understand what's going on. Most will pull over to the shoulder when they see an impatient rider behind them. Once I overtook three guys in pickups, but they didn't look like they wanted to let me by. "Oh no!", I thought. I'm going to have problems getting around these guys. It turns out they were racing. I thoroughly enjoyed following and watching the race. I had little trouble keeping up with them on my Beemer, but these guys knew how to drive those pickups. This is the cream of the crop of roads in that area. It is in the heart of many other great roads, too, generally in the Smoky Mountain National Park area. Gatlinburg, TN is a great place to have dinner and unwind after a tense day of Deal's Gap type of riding. 
          </p>
          <br />
          <br />
          <p>
            Yes, most of my favorites are in the great state of West, BG, Virginia. Of course, the main reason is that the CR is centered there. Another reason is that the 2-lane paved highways are usually in pretty good condition, well marked and the traffic is low. Several years ago, I was watching one of those news magazine shows. I believe it was "20/20". One of the reporters was interviewing Senator Robert Byrd from WV. Senator Byrd had so much seniority in the senate and was still somewhat lucid until the end, that he wielded considerable power. The reporter pointed out to him that in one year, he was able to get fully 50% of the available Federal highway construction funds for WV. Senator Byrd just said one word, "infrastructure!" After watching that program and after a good day of riding the WV highways, I proposed a toast to Sen. Byrd and explained to my biker buddies why. Another tradition started. Now we almost always toast Sen. Byrd after a good day in WV. Sen Byrd has been gone now for some time and on a recent CR I noticed that some of these roads have somewhat deteriorated. I’ve also noticed that many businesses in WV are no longer open. Sen. Byrd surely brought a lot of money into WV. Things do change.
          </p>
        </div>
      </div>
    </div>
  );
}

export default RoadsPage;
